#!/bin/sh
 
mount -t proc none /proc
mount -t sysfs none /sys
mount -t debugfs none /sys/kernel/debug
mount -t devtmpfs none /dev
mknod -m 660 /dev/mem c 1 1

echo -e "\nBoot took $(cut -d' ' -f1 /proc/uptime) seconds\n"
echo "Welcome..."


# Insert any tests that should be executed at startup here

exec setsid cttyhack sh
